apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: "idb"
    access: proxy
    url: http://influx:8086
    user: ''
    database: ''
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: administrator
    withCredentials: false
    isDefault: false
    jsonData:
      defaultBucket: sensor_data
      httpMode: POST
      organization: soa_eews
      version: Flux
    secureJsonData:
      basicAuthPassword: administrator
      token: token
    version: 3
    readOnly: false