services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  database_service:
    container_name: database_service
    build: ../Database Service
    ports:
      - "5000:5000"
    depends_on:
      - "mongodb"
  gateway_service:
    container_name: gateway_service
    build: ../Gateway Service
    depends_on:
      - "database_service"
      - "mqtt"
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  manager:
       image: emqx/ekuiper-manager:latest
       container_name: ekuiper-manager
       ports:
       - "9082:9082"
       restart: unless-stopped
       environment: 
         DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
  ekuiper:
    container_name: ekuiper
    image: lfedge/ekuiper:1.9.1
    ports:
      - "9081:9081"  
      - "127.0.0.1:20498:20498"
    hostname: ekuiper
    restart: unless-stopped
    user: root
    volumes:
     - /tmp/data:/kuiper/data
     - /tmp/log:/kuiper/log
    environment:
         MQTT_SOURCE__DEFAULT__SERVER: "tcp://mqtt:1883"
         KUIPER__BASIC__CONSOLELOG: "true"
         KUIPER__BASIC__IGNORECASE: "false"
    depends_on:
      - "mqtt"
  influx:
    container_name: influx
    image: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=administrator
      - DOCKER_INFLUXDB_INIT_ORG=soa_eews
      - DOCKER_INFLUXDB_INIT_BUCKET=detected_earthquakes
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
    volumes:
      - ./influx/data:/var/lib/influxdb
    ports:
      - "8086:8086"
  analytics_service:
    container_name: analytics_service
    build: ../Analytics Service
    depends_on:
      - "ekuiper"
      - "influx"
      - "mqtt"
      - "notification_service"
  notification_service:
    container_name: notification_service
    build: ../Notification Service
    ports:
      - "50052:50052"
    depends_on:
      - "ekuiper"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influx
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - edgex-network
  visualisation_service:
    container_name: visualisation_service
    build: ../Visualisation Service
    depends_on:
      - "influx"
      - "grafana"
      - "mqtt"