{
 "title": "Dimension_E",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Dimension N",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Earthquake\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Dimension_N\")\r\n  |> aggregateWindow(every: 500000ns, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dimension E",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Earthquake\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Dimension_E\")\r\n  |> aggregateWindow(every: 5ms, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  },
  {
   "title": "Dimension Z",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Earthquake\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Dimension_Z\")\r\n  |> aggregateWindow(every: 5ms, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}